CREATE TABLE DIM_CATEGORIAS(COD_CATEGORIA INTEGER CONSTRAINT PK_CATEGORIA PRIMARY KEY, 
						   DESCRICAO VARCHAR(255) CONSTRAINT NNDESCRICAO NOT NULL);
						   
CREATE TABLE DIM_TIPO(COD_TIPO INTEGER CONSTRAINT PK_TIPO PRIMARY KEY, 
						   DESCRICAO VARCHAR(255) CONSTRAINT NNDESCRICAO NOT NULL);				
						   
CREATE TABLE DIM_PRODUTOS(COD_PRODUTO INTEGER CONSTRAINT PK_PRODUTO PRIMARY KEY, 
						  COD_CATEGORIA INTEGER CONSTRAINT NNCOD_CATEGORIA NOT NULL, 
						  COD_TIPO INTEGER CONSTRAINT NNCOD_TIPO NOT NULL,
						  DESCRICAO VARCHAR(255) CONSTRAINT NNDESCRICAO NOT NULL,
						  CONSTRAINT FK_DIM_PRODUTOS_DIM_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES DIM_CATEGORIAS(COD_CATEGORIA),
						  CONSTRAINT FK_DIM_PRODUTOS_DIM_TIPO FOREIGN KEY (COD_TIPO) REFERENCES DIM_TIPO(COD_TIPO));
						 
CREATE TABLE DIM_TEMPO(COD_TEMPO INTEGER CONSTRAINT PK_TEMPO PRIMARY KEY,
					   ANO INTEGER CONSTRAINT NNANO NOT NULL,
					   MES INTEGER CONSTRAINT NNMES NOT NULL);	
					   
CREATE TABLE DIM_LOJA(COD_LOJA INTEGER CONSTRAINT PK_LOJA PRIMARY KEY,
					  NOME_LOJA VARCHAR(255) CONSTRAINT NNNOME_LOJA NOT NULL);
					  
CREATE TABLE DIM_CLIENTES(CPF NUMERIC(15) CONSTRAINT PK_CLIENTES PRIMARY KEY,
						  NOME VARCHAR (255) CONSTRAINT NNNOME NOT NULL);
						  
CREATE TABLE DIM_FORNECEDORES(COD_FORNECEDOR INTEGER CONSTRAINT PK_FORNECEDORES PRIMARY KEY,
   						   	  RAZAO_SOCIAL VARCHAR (255) CONSTRAINT NNRAZAO_SOCIAL NOT NULL);
							
CREATE TABLE DIM_FUNCIONARIOS(MATRICULA INTEGER CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY,
							  NOME_FUNCIONARIO VARCHAR (255) CONSTRAINT NNNOME_FUNCIONARIO NOT NULL);
							  
CREATE TABLE FATO_VENDA(COD_VENDA INTEGER CONSTRAINT PK_FATO_VENDA PRIMARY KEY, 
					   	QUANTIDADE DECIMAL(10,4),
					   	VALOR_TOTAL DECIMAL (10,2) CONSTRAINT NNVALOR_TOTAL NOT NULL,
					    COD_PRODUTO INTEGER,
					   	COD_TEMPO INTEGER CONSTRAINT NNCOD_TEMPO NOT NULL,
					   	COD_CATEGORIA INTEGER,
					   	COD_LOJA INTEGER,
					   	CPF NUMERIC(15),
					   	MATRICULA INTEGER, 
					   	CONSTRAINT FK_FATO_VENDA_DIM_PRODUTOS FOREIGN KEY (COD_PRODUTO) REFERENCES DIM_PRODUTOS(COD_PRODUTO),
						CONSTRAINT FK_FATO_VENDA_DIM_TEMPO FOREIGN KEY (COD_TEMPO) REFERENCES DIM_TEMPO(COD_TEMPO),
						CONSTRAINT FK_FATO_VENDA_DIM_CATEGORIAS FOREIGN KEY (COD_CATEGORIA) REFERENCES DIM_CATEGORIAS(COD_CATEGORIA),
						CONSTRAINT FK_FATO_VENDA_DIM_LOJA FOREIGN KEY (COD_LOJA) REFERENCES DIM_LOJA(COD_LOJA),
						CONSTRAINT FK_FATO_VENDA_DIM_CLIENTES FOREIGN KEY (CPF) REFERENCES DIM_CLIENTES(CPF),
						CONSTRAINT FK_FATO_VENDA_DIM_FUNCIONARIOS FOREIGN KEY (MATRICULA) REFERENCES DIM_FUNCIONARIOS(MATRICULA));
						
						
CREATE TABLE FATO_COMPRA(COD_COMPRA INTEGER CONSTRAINT PK_FATO_COMPRA PRIMARY KEY, 
					   	 QUANTIDADE DECIMAL(10,4),
					   	 VALOR_TOTAL DECIMAL (10,2) CONSTRAINT NNVALOR_TOTAL NOT NULL,
					     VALOR DECIMAL(10,2),					   	 					   	
					   	 COD_LOJA INTEGER,
						 COD_TEMPO INTEGER CONSTRAINT NNCOD_TEMPO NOT NULL,
					   	 COD_FORNECEDOR INTEGER,
						 COD_PRODUTO INTEGER,
						 CONSTRAINT FK_FATO_COMPRA_DIM_LOJA FOREIGN KEY (COD_LOJA) REFERENCES DIM_LOJA(COD_LOJA),
						 CONSTRAINT FK_FATO_COMPRA_DIM_TEMPO FOREIGN KEY (COD_TEMPO) REFERENCES DIM_TEMPO(COD_TEMPO),
						 CONSTRAINT FK_FATO_COMPRA_DIM_FORNECEDORES FOREIGN KEY (COD_FORNECEDOR) REFERENCES DIM_FORNECEDORES(COD_FORNECEDOR),
						 CONSTRAINT FK_FATO_COMPRA_DIM_PRODUTOS FOREIGN KEY (COD_PRODUTO) REFERENCES DIM_PRODUTOS(COD_PRODUTO));						
					 	
						

						  
						  